# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_cost1_ <- function(x, y) {
    .Call('CoupledPF_compute_cost1_', PACKAGE = 'CoupledPF', x, y)
}

compute_cost2_ <- function(x, y) {
    .Call('CoupledPF_compute_cost2_', PACKAGE = 'CoupledPF', x, y)
}

cost_matrix_ <- function(x, y) {
    .Call('CoupledPF_cost_matrix_', PACKAGE = 'CoupledPF', x, y)
}

square_cost_matrix_ <- function(x, y) {
    .Call('CoupledPF_square_cost_matrix_', PACKAGE = 'CoupledPF', x, y)
}

create_A_ <- function(alpha, d) {
    .Call('CoupledPF_create_A_', PACKAGE = 'CoupledPF', alpha, d)
}

hilbert_order_ <- function(x) {
    .Call('CoupledPF_hilbert_order_', PACKAGE = 'CoupledPF', x)
}

indexmatching_cpp <- function(ndraws, w1, w2, uniforms) {
    .Call('CoupledPF_indexmatching_cpp', PACKAGE = 'CoupledPF', ndraws, w1, w2, uniforms)
}

kalman_loglikelihood_ <- function(parameters, observations) {
    .Call('CoupledPF_kalman_loglikelihood_', PACKAGE = 'CoupledPF', parameters, observations)
}

kalman_filtering_means_ <- function(parameters, observations) {
    .Call('CoupledPF_kalman_filtering_means_', PACKAGE = 'CoupledPF', parameters, observations)
}

kalman_smoothing_means_ <- function(parameters, observations) {
    .Call('CoupledPF_kalman_smoothing_means_', PACKAGE = 'CoupledPF', parameters, observations)
}

malikpitt_ <- function(xparticles, weights, u) {
    .Call('CoupledPF_malikpitt_', PACKAGE = 'CoupledPF', xparticles, weights, u)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('CoupledPF_rmvnorm', PACKAGE = 'CoupledPF', nsamples, mean, covariance)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('CoupledPF_dmvnorm', PACKAGE = 'CoupledPF', x, mean, covariance)
}

one_step_pz_ <- function(P, Z, t, alpha, c, e, ml, mq) {
    .Call('CoupledPF_one_step_pz_', PACKAGE = 'CoupledPF', P, Z, t, alpha, c, e, ml, mq)
}

one_step_pz_vector <- function(xparticles, alphas, t, parameters) {
    .Call('CoupledPF_one_step_pz_vector', PACKAGE = 'CoupledPF', xparticles, alphas, t, parameters)
}

systematic_resampling_n_ <- function(weights, ndraws, u) {
    .Call('CoupledPF_systematic_resampling_n_', PACKAGE = 'CoupledPF', weights, ndraws, u)
}

wasserstein_auto_ <- function(p_, q_, cost_matrix_, epsilon, desired_alpha) {
    .Call('CoupledPF_wasserstein_auto_', PACKAGE = 'CoupledPF', p_, q_, cost_matrix_, epsilon, desired_alpha)
}

