# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ar_rinit_rcpp <- function(nparticles, theta, rand, dimension) {
    .Call('CoupledCPF_ar_rinit_rcpp', PACKAGE = 'CoupledCPF', nparticles, theta, rand, dimension)
}

ar_rtransition_rcpp <- function(xparticles, theta, time, rand, dimension, A) {
    .Call('CoupledCPF_ar_rtransition_rcpp', PACKAGE = 'CoupledCPF', xparticles, theta, time, rand, dimension, A)
}

indexmatching_cpp <- function(ndraws, w1, w2, uniforms) {
    .Call('CoupledCPF_indexmatching_cpp', PACKAGE = 'CoupledCPF', ndraws, w1, w2, uniforms)
}

create_A_ <- function(alpha, d) {
    .Call('CoupledCPF_create_A_', PACKAGE = 'CoupledCPF', alpha, d)
}

hilbert_order_ <- function(x) {
    .Call('CoupledCPF_hilbert_order_', PACKAGE = 'CoupledCPF', x)
}

levydriven_rtransition_rand_cpp <- function(nparticles, theta) {
    .Call('CoupledCPF_levydriven_rtransition_rand_cpp', PACKAGE = 'CoupledCPF', nparticles, theta)
}

levydrivenmultifactor_rtransition_rand_cpp <- function(nparticles, theta) {
    .Call('CoupledCPF_levydrivenmultifactor_rtransition_rand_cpp', PACKAGE = 'CoupledCPF', nparticles, theta)
}

median_rcpp <- function(x) {
    .Call('CoupledCPF_median_rcpp', PACKAGE = 'CoupledCPF', x)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('CoupledCPF_rmvnorm', PACKAGE = 'CoupledCPF', nsamples, mean, covariance)
}

rmvnorm_transpose <- function(nsamples, mean, covariance) {
    .Call('CoupledCPF_rmvnorm_transpose', PACKAGE = 'CoupledCPF', nsamples, mean, covariance)
}

rmvnorm_transpose_cholesky <- function(nsamples, mean, cholesky_covariance) {
    .Call('CoupledCPF_rmvnorm_transpose_cholesky', PACKAGE = 'CoupledCPF', nsamples, mean, cholesky_covariance)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('CoupledCPF_dmvnorm', PACKAGE = 'CoupledCPF', x, mean, covariance)
}

dmvnorm_transpose <- function(x, mean, covariance) {
    .Call('CoupledCPF_dmvnorm_transpose', PACKAGE = 'CoupledCPF', x, mean, covariance)
}

dmvnorm_transpose_cholesky <- function(x, mean, cholesky_covariance) {
    .Call('CoupledCPF_dmvnorm_transpose_cholesky', PACKAGE = 'CoupledCPF', x, mean, cholesky_covariance)
}

one_step_pz_vector <- function(xparticles, alphas, t, parameters) {
    .Call('CoupledCPF_one_step_pz_vector', PACKAGE = 'CoupledCPF', xparticles, alphas, t, parameters)
}

stochvol_dmeas_ <- function(xparticles, theta, observation, dimension) {
    .Call('CoupledCPF_stochvol_dmeas_', PACKAGE = 'CoupledCPF', xparticles, theta, observation, dimension)
}

systematic_resampling_n_ <- function(weights, ndraws, u) {
    .Call('CoupledCPF_systematic_resampling_n_', PACKAGE = 'CoupledCPF', weights, ndraws, u)
}

